// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package lokr

import (
	"context"
	"database/sql"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *sql.DB, driverName string, isDebugMode bool) (*Lokr, error) {
	lokrRepository, err := ProvideLokrRepository(db, driverName)
	if err != nil {
		return nil, err
	}
	lokr, err := ProvideLokr(lokrRepository, isDebugMode)
	if err != nil {
		return nil, err
	}
	return lokr, nil
}
