// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// JobHandler is an autogenerated mock type for the JobHandler type
type JobHandler struct {
	mock.Mock
}

type JobHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *JobHandler) EXPECT() *JobHandler_Expecter {
	return &JobHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *JobHandler) Handle(_a0 context.Context, _a1 string) {
	_m.Called(_a0, _a1)
}

// JobHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type JobHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 string
func (_e *JobHandler_Expecter) Handle(_a0 interface{}, _a1 interface{}) *JobHandler_Handle_Call {
	return &JobHandler_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *JobHandler_Handle_Call) Run(run func(_a0 context.Context, _a1 string)) *JobHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *JobHandler_Handle_Call) Return() *JobHandler_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *JobHandler_Handle_Call) RunAndReturn(run func(context.Context, string)) *JobHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewJobHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewJobHandler creates a new instance of JobHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJobHandler(t mockConstructorTestingTNewJobHandler) *JobHandler {
	mock := &JobHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
